# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'labeller.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.6
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#
# from PyQt5 import QtCore, QtGui, QtWidgets
#
#
# class Ui_Labeller(QtWidgets):
#     def setupUi(self, Labeller):
#         Labeller.setObjectName("Labeller")
#         Labeller.resize(415, 756)
#         self.centralwidget = QtWidgets.QWidget(Labeller)
#         self.centralwidget.setObjectName("centralwidget")
#         self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
#         self.verticalLayout_2.setObjectName("verticalLayout_2")
#         self.verticalLayout = QtWidgets.QVBoxLayout()
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.logger=QtWidgets.QTextEdit(self.centralwidget)
#         # self.listView = QtWidgets.QListView(self.centralwidget)
#         # self.listView.setObjectName("listView")
#         self.verticalLayout.addWidget(self.logger)
#         self.horizontalLayout = QtWidgets.QHBoxLayout()
#         self.horizontalLayout.setObjectName("horizontalLayout")
#         self.btn_patchAtk = QtWidgets.QPushButton(self.centralwidget)
#         self.btn_patchAtk.setObjectName("btn_patchAtk")
#         self.horizontalLayout.addWidget(self.btn_patchAtk)
#         self.btn_otherAtk = QtWidgets.QPushButton(self.centralwidget)
#         self.btn_otherAtk.setObjectName("btn_otherAtk")
#         self.horizontalLayout.addWidget(self.btn_otherAtk)
#         self.btn_noneAtk = QtWidgets.QPushButton(self.centralwidget)
#         self.btn_noneAtk.setObjectName("btn_noneAtk")
#         self.horizontalLayout.addWidget(self.btn_noneAtk)
#         self.btn_question = QtWidgets.QPushButton(self.centralwidget)
#         self.btn_question.setObjectName("btn_question")
#         self.horizontalLayout.addWidget(self.btn_question)
#         self.verticalLayout.addLayout(self.horizontalLayout)
#         self.verticalLayout_2.addLayout(self.verticalLayout)
#         Labeller.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(Labeller)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 26))
#         self.menubar.setObjectName("menubar")
#         Labeller.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(Labeller)
#         self.statusbar.setObjectName("statusbar")
#         Labeller.setStatusBar(self.statusbar)
#         self.toolBar = QtWidgets.QToolBar(Labeller)
#         self.toolBar.setObjectName("toolBar")
#         # Labeller.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
#
#         self.retranslateUi(Labeller)
#         QtCore.QMetaObject.connectSlotsByName(Labeller)
#
#     def retranslateUi(self, Labeller):
#         _translate = QtCore.QCoreApplication.translate
#         Labeller.setWindowTitle(_translate("Labeller", "MainWindow"))
#         self.btn_patchAtk.setText(_translate("Labeller", "Patch攻击"))
#         self.btn_otherAtk.setText(_translate("Labeller", "其他攻击"))
#         self.btn_noneAtk.setText(_translate("Labeller", "无攻击"))
#         self.btn_question.setText(_translate("Labeller", "有疑问"))
#         # self.toolBar.setWindowTitle(_translate("Labeller", "toolBar"))
